# Generated by Django 3.1.5 on 2021-01-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apimodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.CharField(max_length=100)),
                ('sample', models.CharField(max_length=100)),
                ('sleeping', models.CharField(max_length=100)),
                ('playing', models.CharField(max_length=100)),
                ('learning', models.CharField(max_length=100)),
            ],
        ),
    ]
