# Generated by Django 3.1.5 on 2021-01-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apimodel',
            old_name='quiz',
            new_name='Quiz',
        ),
        migrations.RenameField(
            model_name='apimodel',
            old_name='sample',
            new_name='sampletest',
        ),
    ]
